# Generated by Django 5.0.7 on 2024-09-05 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=10000)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('sale_amount', models.BigIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=100)),
                ('payment_url', models.URLField(default='https://www.google.com', max_length=400)),
                ('sale_status', models.CharField(choices=[('pending', '🟡 Pending'), ('payed', '💸 Payed'), ('on_delivery', '✈️ On delivery'), ('delivered', '🟢 Delivered')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
