# Generated by Django 5.0.7 on 2024-08-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(default='https://www.google.com', max_length=400),
        ),
    ]
