# Generated by Django 5.0.7 on 2024-08-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='sale_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
