version: '3.11'

services:
  db:
    container_name: db-service
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: web-service
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  redis:
    container_name: redis-service
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
