version: '3.11'

services:
  db:
    container_name: db-service
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: web-service
    build: .
    command: gunicorn core.wsgi:application --bind ${HOST}:${PORT} --log-level debug
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env
  redis:
    container_name: redis-service
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  postgres_data:
